import "./globals.css";
import Layout from "../components/layout/Layout";
import { yekan } from "../utils/fonts";
import { ThemeProvider } from "next-themes";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={yekan.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
