import "./globals.css";
import Layout from "../components/layout/Layout";
import { yekan } from "../utils/fonts";
import { ThemeProvider } from "next-themes";
import NextAuthProvider from "../providers/NextAuthProvider";
import { CartProvider } from "../context/CartContext";
// import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={yekan.className}>
        <NextAuthProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <CartProvider>
              <Layout>{children}</Layout>
            </CartProvider>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
